---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rendszam-frontend-certificate
spec:
  secretName: rendszamgen-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - rendszam.jcloud.jedlik.cloud
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rendszam-deployment
spec:
  selector:
    matchLabels:
      app: rendszamgen
  template:
    metadata:
      labels:
        app: rendszamgen
    spec:
      imagePullSecrets:
        - name: ghcr-login-secret
      containers:
        - name: rendszamgen
          image: ghcr.io/kriszchan/rendszamgen:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: rendszamgen-cluster-ip-service
spec:
  selector:
    app: rendszamgen
  type: ClusterIP
  ports:
    - protocol: TCP
      targetPort: 80
      port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rendszamgen-ingress
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - rendszam.jcloud.jedlik.cloud
    secretName: rendszamgen-certificate

  rules:
    - host: rendszam.jcloud.jedlik.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rendszamgen-cluster-ip-service
                port:
                  number: 80
---
